export const ROBOTS = [
    { id: 'siget', name: 'WebSiget' },
    { id: 'cnt', name: 'WebCnt' },
    { id: 'pantanal', name: 'WebPantanal' },
    { id: 'assu', name: 'WebAssu' },
    { id: 'tropicalia', name: 'WebTropicalia' },
    { id: 'firminopolis', name: 'WebFirminopolis' },
    { id: 'evoltz', name: 'WebEvoltz' },
    { id: 'guaira', name: 'WebGuaira' },
    { id: 'itamaraca', name: 'WebItamaraca' },
    { id: 'colinas', name: 'WebColinas' },
    { id: 'simoes', name: 'WebSimoes' },
    { id: 'fs', name: 'WebFS' },
    { id: 'vineyards', name: 'WebVineyards' },
    { id: 'agua_vermelha', name: 'WebAguaVermelha' },
    { id: 'webieriachogrande', name: 'WebIERIACHOGRANDE', type: 'ie' },
    { id: 'webiecteep', name: 'WebIECTEEP', type: 'ie' },
    { id: 'webieaguapei', name: 'WebIEAGUAPEI', type: 'ie' },
    { id: 'webiebiguacu', name: 'WebIEBIGUACU', type: 'ie' },
    { id: 'webiegaranhuns', name: 'WebIEGARANHUNS', type: 'ie' },
    { id: 'webieitapura', name: 'WebIEITAPURA', type: 'ie' },
    { id: 'webieitaquere', name: 'WebIEITAQUERE', type: 'ie' },
    { id: 'webieitaunas', name: 'WebIEITAUNAS', type: 'ie' },
    { id: 'webieivai', name: 'WebIEIVAI', type: 'ie' },
    { id: 'webiejaguar6', name: 'WebIEJAGUAR6', type: 'ie' },
    { id: 'webiejaguar8', name: 'WebIEJAGUAR8', type: 'ie' },
    { id: 'webiejaguar9', name: 'WebIEJAGUAR9', type: 'ie' },
    { id: 'webiemadeira', name: 'WebIEMADEIRA', type: 'ie' },
    { id: 'webiemg', name: 'WebIEMG', type: 'ie' },
    { id: 'webienne', name: 'WebIENNE', type: 'ie' },
    { id: 'webiepinheiros', name: 'WebIEPINHEIROS', type: 'ie' },
    { id: 'webieserradojapi', name: 'WebIESERRADOJAPI', type: 'ie' },
    { id: 'webiesul', name: 'WebIESUL', type: 'ie' },
    { id: 'webietibagi', name: 'WebIETIBAGI', type: 'ie' },
    { id: 'webengie', name: 'WebEngie' },
    { id: 'webettm', name: 'WebETTM' },
    { id: 'websigetpublic', name: 'WebSigetPublic' },
]
