export const ROBOTS = [
    { id: 'siget', name: 'WebSiget' },
    { id: 'eletrobras', name: 'WebEletrobras' },
    { id: 'cnt', name: 'WebCnt' },
    { id: 'pantanal', name: 'WebPantanal' },
    { id: 'assu', name: 'WebAssu' },
    { id: 'tropicalia', name: 'WebTropicalia' },
    { id: 'firminopolis', name: 'WebFirminopolis' },
    { id: 'evoltz', name: 'WebEvoltz' },
    { id: 'guaira', name: 'WebGuaira' },
    { id: 'itamaraca', name: 'WebItamaraca' },
    { id: 'colinas', name: 'WebColinas' },
    { id: 'simoes', name: 'WebSimoes' },
    { id: 'fs', name: 'WebFS' },
    { id: 'vineyards', name: 'WebVineyards' },
    { id: 'agua_vermelha', name: 'WebAguaVermelha' },
    { id: 'webieriachogrande', name: 'WebIERIACHOGRANDE', type: 'ie' },
    { id: 'webiecteep', name: 'WebIECTEEP', type: 'ie' },
    { id: 'webieaguapei', name: 'WebIEAGUAPEI', type: 'ie' },
    { id: 'webiebiguacu', name: 'WebIEBIGUACU', type: 'ie' },
    { id: 'webiegaranhuns', name: 'WebIEGARANHUNS', type: 'ie' },
    { id: 'webieitapura', name: 'WebIEITAPURA', type: 'ie' },
    { id: 'webieitaquere', name: 'WebIEITAQUERE', type: 'ie' },
    { id: 'webieitaunas', name: 'WebIEITAUNAS', type: 'ie' },
    { id: 'webieivai', name: 'WebIEIVAI', type: 'ie' },
    { id: 'webiejaguar6', name: 'WebIEJAGUAR6', type: 'ie' },
    { id: 'webiejaguar8', name: 'WebIEJAGUAR8', type: 'ie' },
    { id: 'webiejaguar9', name: 'WebIEJAGUAR9', type: 'ie' },
    { id: 'webiemadeira', name: 'WebIEMADEIRA', type: 'ie' },
    { id: 'webiemg', name: 'WebIEMG', type: 'ie' },
    { id: 'webienne', name: 'WebIENNE', type: 'ie' },
    { id: 'webiepinheiros', name: 'WebIEPINHEIROS', type: 'ie' },
    { id: 'webieserradojapi', name: 'WebIESERRADOJAPI', type: 'ie' },
    { id: 'webiesul', name: 'WebIESUL', type: 'ie' },
    { id: 'webietibagi', name: 'WebIETIBAGI', type: 'ie' },
    { id: 'webengie', name: 'WebEngie' },
    { id: 'webettm', name: 'WebETTM' },
    { id: 'websigetpublic', name: 'WebSigetPublic' },
    { id: 'webtaesa', name: 'WebTaesa' },
    { id: 'celeo', name: 'WebCeleo' },
    { id: 'web_ie', name: 'WebIE(ISA)' },
    { id: 'arteon', name: 'WebArteon' },
    { id: 'light', name: 'WebLight' },
    { id: 'equatorial', name: 'WebEquatorial' },
    { id: 'equatorial_v2', name: 'WebEquatorial V2' },
    { id: 'rialmas', name: 'WebRialmas' },
    { id: 'rialmav', name: 'WebRialmaV' },
    { id: 'rialmaiv', name: 'WebRialmaIV' },
    { id: 'aete', name: 'WebAETE' },
    { id: 'transnorte', name: 'WebTransnorte' },
    { id: 'cpfl', name: 'WebCPFL' },
    { id: 'glorian', name: 'WebGlorian' },
    { id: 'copel', name: 'WebCopel' },
    { id: 'mge', name: 'WebMGE' },
    { id: 'stategrid', name: 'WebStateGrid' },
    { id: 'stn', name: 'WebSTN' },
    { id: 'tecp', name: 'WebTECP' },
    { id: 'elte', name: 'WebELTE' },
    { id: 'etes', name: 'WebETES' },
    { id: 'tme', name: 'WebTME' },
    { id: 'etem', name: 'WebETEM' },
    { id: 'etvg', name: 'WebETVG' },
    { id: 'tne', name: 'WebTNE' },
    { id: 'etc', name: 'WebETC' },
    { id: 'etap', name: 'WebETAP' },
    { id: 'tcc', name: 'WebTCC' },
    { id: 'tpe', name: 'WebTPE' },
    { id: 'tsm', name: 'WebTSM' },
    { id: 'etb', name: 'WebETB' },
    { id: 'amazonia', name: 'WebAmazonia' },
    { id: 'tcpe', name: 'WebTCPE' },
    { id: 'vsb', name: 'WebVSB' },
    { id: 'verene', name: 'WebVerene' },
    { id: 'tbe', name: 'WebTBE' },
    { id: 'ons', name: 'WebOns' },
    { id: 'harpix', name: 'WebHarpix' },
    { id: 'cemig', name: 'WebCemig' },
    { id: 'rio_largo', name: 'WebRioLargo' },
    { id: 'etepa', name: 'WebEtepa' },
    { id: 'etene', name: 'WebEtene' },
    { id: 'lnt', name: 'WebLNT' },
    { id: 'sigetplusv2', name: 'WebSigetPlusV2' },
]
